### ISSUE TITLE
Report generation likely to generate bad paths on Windows

### ISSUE THREAD

**Issue by taldcroft** [sot/aca_preview#21]
By default `Path` will use the local path separator, which is generally a good thing unless you are making local paths for output to HTML.  I suspect relative URL links in the reports will look like `obs12345\index.html` when created on Windows.

The fix is (I think) to explicitly use `PosixPath` for paths intended for generating HTML link paths.

**Comment by jeanconn** [comment]
I think we are at the point where we should cut a beta release for windows testing.

**Comment by taldcroft** [comment]
Agreed.  But I would call it alpha since it doesn't include #19 which is starting to come together.

**Comment by taldcroft** [comment]
In fact I think I will have something on #19 that is ready for review in the next hour.

**Comment by jeanconn** [comment]
Whereas I'd want to call it alpha *if* it included #19 .  But would also need to cut a testing release of proseco to accompany.
