### ISSUE TITLE
'all' level doesn't work the way I would expect

### ISSUE THREAD

**Issue by jeanconn** [sot/aca_preview#25]
I was expecting full acq and guide reporting and a roll report and got just a plain report with:
```
fido: python -m aca_preview.preview JAN2119B --report-level=all --roll-level=all --obsid 48487
Reading pickle file JAN2119B_proseco.pkl
Processing obsid 48487
Writing output review file JAN2119B_aca_preview/index.html
```

**Comment by jeanconn** [comment]
Though this may be related to the fact that it looks like the reporting and roll exploring is just broken after I stripped out the mag_err change.  So will see which things get fixed when that is back.

**Comment by taldcroft** [comment]
Gah, my bad.  Fixing, and adding tests.
