### ISSUE TITLE
Make aca_preview 4.3.x compatible

### ISSUE THREAD

**Issue by jeanconn** [sot/aca_preview#5]
It looks like I've got a conflict when trying to run from a pickle against proseco 4.3.2 (checked out in my ~/git/proseco below) which is what I believe we'd be running against if we try to install this in ska3-matlab.  I don't think 4.3.x has the updates to re-instantiate the bad_stars mask?  So then I'm not sure if we want to fix in that in proseco 4.3.x or call separate custom plotting in aca_preview.

```
/proj/sot/ska/jeanproj/git/aca_preview/aca_preview/preview.py in make_starcat_plot(self)
    145         ax = fig.add_subplot(1, 1, 1)
    146         self.acqs.stars
--> 147         self.plot(ax=ax)
    148         plt.tight_layout()
    149         fig.savefig(str(outfile))

~/git/proseco/proseco/core.py in plot(self, ax)
    493         if self.acqs:
    494             stars_kwargs['stars'] = self.acqs.stars
--> 495             stars_kwargs['bad_stars'] = self.acqs.bad_stars
    496 
    497         plot_stars(attitude=self.att, catalog=self, ax=ax, **stars_kwargs)

AttributeError: 'AcqTable' object has no attribute 'bad_stars'
```

**Comment by jeanconn** [comment]
aca_preview is also references proseco.characteristics with attributes that aren't in 4.3.2 .

**Comment by taldcroft** [comment]
This bug has been here and there for a while.  Hopefully just setting it to None does the trick.

But the second comment is more of an issue.

**Comment by jeanconn** [comment]
OK.  I thought it might be easier just to not call the plotting from proseco, hence ideas in #6  (which also just hard codes the CHAR that are moved around in proseco).  I thought about using LooseVersion to get the characteristics from the different proseco versions in the different places but that seemed not the point of the aca_preview package.

**Comment by jeanconn** [comment]
Yep.  And I thought the version of proseco in the environment mattered a bit more than the one that saved the pickle, but both relevant to releasing the tool.
